# Generated by Django 6.0.6 on 2026-07-31 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_address_order_city_order_customer_name_and_more'),
        ('shop', '0005_product_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
