# Generated by Django 6.0.7 on 2026-07-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_address_profile_favorites_profile_phone'),
        ('shop', '0006_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorites',
        ),
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourited_by', to='shop.product'),
        ),
    ]
