# Generated by Django 6.0.6 on 2026-07-10 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_size_product_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='products', related_query_name='product', to='shop.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=None, null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.brand'),
            preserve_default=False,
        ),
    ]
